version: '3.8'

services:
  icp-bets:
    build: .
    container_name: icp-bets-platform
    ports:
      - "8000:8000"   # DFX local network
      - "3000:3000"   # Frontend (if needed)
      - "4943:4943"   # Internet Identity
    volumes:
      - ./.dfx:/app/.dfx  # Persist DFX data
      - ./canister-ids.json:/app/canister-ids.json  # Persist canister IDs
    environment:
      - DFX_NETWORK=local
    restart: unless-stopped
    stdin_open: true
    tty: true

  # Optional: Add a simple web interface to view canister status
  icp-dashboard:
    image: nginx:alpine
    container_name: icp-bets-dashboard
    ports:
      - "8080:80"
    volumes:
      - ./dashboard.html:/usr/share/nginx/html/index.html
    depends_on:
      - icp-bets
    restart: unless-stopped 