version: '3.8'

services:
  icp-bets-minimal:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: icp-bets-minimal
    ports:
      - "8000:8000"   # DFX local network
      - "3000:3000"   # Frontend dev server
      - "4943:4943"   # Internet Identity
    volumes:
      - ./.dfx:/app/.dfx  # Persist DFX data
      - ./canister-ids.json:/app/canister-ids.json  # Persist canister IDs
      - ./src:/app/src  # Mount source code for development
    environment:
      - DFX_NETWORK=local
    stdin_open: true
    tty: true
    working_dir: /app 